### ISSUE TITLE
Ruimte gebruik filter

### ISSUE THREAD

**Issue by MokhtarAkle** [Tristandemuijnck/connect-your-tribe-squad-page#12]
Het huidige filter plaatst alle elementen verticaal, op grotere schermen is het handiger om dit horizontaal neer te zetten om beter gebruik te maken van de grootte.

**Comment by Tristandemuijnck** [comment]
Fixed with media query

![image](https://user-images.githubusercontent.com/43402897/220758616-76e85c2d-3a75-4469-9db8-3e7c4da46153.png)
